language: java
jdk:
  - openjdk13

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

sudo: false

notifications:
  email:
    recipients:
      - shein.v94@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
